### PR TITLE
Adding Sharp GP2Y0A21F_5V_DS

### PR DESCRIPTION
**Pull request by cgo**
I have added values for the sensor that I found in my junk box. The values are from a power function fit that I did 
by reading the values roughly from the plot provided in the datasheet. There is unfortunately no actual data.
The readings are not super accurate, but good enough for my purposes.

### CODE REVIEW

**Comment by DrGFreeman** [comment]
Hey @cgo, thanks for taking the time to make this contribution so others can benefit from it!

The code changes look good to me and the [CI checks](https://travis-ci.org/github/DrGFreeman/SharpDistSensor/builds/726860328) passed on all boards.

Do you have the "advertised" range (in cm) of the sensor and would you mind also updating the information on the README ([list of models](https://github.com/DrGFreeman/SharpDistSensor#pre-defined-sensor-models), [coefficients table](https://github.com/DrGFreeman/SharpDistSensor#polynomial--power-fit-coefficients) and [analog range table](https://github.com/DrGFreeman/SharpDistSensor#analog-values-range))?

Thanks!

**Comment by cgo** [comment]
Hey @DrGFreeman, wow you're running a CI for this; nice!
I believe the range is said to be 10-80cm, but I would not bet my life on the output of that sensor. Using my hand, it seems more or less accurate up to a few cm (up to the calibration that I did by reading values off the graph in the datasheet). The further away, the larger the error seems to be, which is not surprising. The analog range in the code I set to [0,1023]; that limits the read voltage, right? I didn't want to limit it because of the apparent inaccuracies. The lower voltage limit in the datasheet says 0.4V, I think, which would be 409 or 410 in the codomain of the readAnalog function.

I also noticed that the values for the other sensors in the README are given in mm; the output for the one I added is in cm. Given the apparent accuracy, I think that is more than enough; do you want all of them to be in mm?

**Comment by cgo** [comment]
Looks like my emacs has cleaned up some whitespace -- if that's bothersome, I can undo that too.

**Comment by DrGFreeman** [comment]
Hi @cgo, thanks for the update of the README. No problem with the whitespaces, it's cleaner like this actually.

> wow you're running a CI for this; nice!

Not much merit on my part, I just copied what Pololu are doing for their Arduino library. Basically checks that the example sketches compile OK, no more but useful nevertheless.

>I believe the range is said to be 10-80cm, but I would not bet my life on the output of that sensor.

Agree, this is mostly for the list of models in the README to help people identify which sensor they have as it's easy to get mixed up in the Sharp model numbers. The range in cm can help confirm the model is the right one. I see you added it in the README, that's perfect. Thanks.

> The analog range in the code I set to [0,1023]; that limits the read voltage, right? I didn't want to limit it because of the apparent inaccuracies.

That's fine, especially with a power function, extrapolation is not as bad as with a polynomial which can give unexpected results outside of the calibrated range.

> I also noticed that the values for the other sensors in the README are given in mm; the output for the one I added is in cm.

I would prefer the output to be in mm for consistency with the other models (the [Library Reference](https://github.com/DrGFreeman/SharpDistSensor#library-reference) says the output of the `getDist()` method is in mm) as well as to provide better resolution (resolution != accuracy) since the output is of integer type. This, along with the median filter included in the library, can provide smoother output which in turn can help control systems like PID controllers provide a smoother response when using the distance output as input.

**Comment by DrGFreeman** [comment]
Also, I forgot to ask if you could add the model in the [`keywords.txt`](https://github.com/DrGFreeman/SharpDistSensor/blob/master/keywords.txt) with the `LITERAL1` value (tab delimited). This allows the model name to highlight in the Arduino IDE.

Thanks again!

**Comment by cgo** [comment]
I think I addressed all issues, let me know if there's something else or feel free to make modifications :)

**Comment by DrGFreeman** [comment]
> I think I addressed all issues, let me know if there's something else or feel free to make modifications :)

Thanks @cgo. I made minor modifications to maintain the line breaks in the README file and tab spacing in `keywords.txt`.

This is ready to merge. Thanks again for your contribution!

I will proceed to make a new release (#18) shortly so the new version is available in the Arduino Library Manager.

**Comment by cgo** [comment]
> This is ready to merge. Thanks again for your contribution!

You're welcome. Thanks for making this library available!

> I will proceed to make a new release (#18) shortly so the new version is available in the Arduino Library Manager.

Sweet!

**Pull request merged**
